[package]
name = "craft"
version = "0.1.0"
authors = ["lwansbrough <lochie@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.2"
bincode = "1.3.1"
serde = "1.0.*"
log = "0.4.8"
